### ISSUE TITLE
Something's wrong with the result

### ISSUE THREAD

**Issue by nxddsnc** [bhaettasch/pop-buffer-demo#1]
Hi,
I just download your project and tested it. But there seems to be some problems with the mesh's indexes.  It looks like this=>http://pan.baidu.com/s/1mhXbhOk. Am I doing something wrong or there's a bug with the program?

**Comment by bhaettasch** [comment]
Hey,
it looks like your Webserver does not support partial requests but always offers the same content independed of which range was requestet. This results in downloading the whole file multiple times and istead of adding the missing parts to the buffer always adding the first blocks of data again. I experienced the same with the simple HTTP server build into Jetbrains Webstorm.

I will probably add a function to detect the content size to fix this for those kind of webservers in the next few days. Please be aware that the whole project is still work in progress and does currently not correctly implement the POP buffer as described by the x3dom team.

**Comment by bhaettasch** [comment]
I created a ticket ( #2 ) to support also webservers without partial request ability.

**Comment by bhaettasch** [comment]
Please check if another webserver solves your problem so I can close this ticket.

**Comment by bhaettasch** [comment]
I implemented the correct handling for servers without partial request, so this problem should be fixed now. Please reopen this issue if the problem persists with the current version of the code.
