### ISSUE TITLE
Detect content size and handle correctly

### ISSUE THREAD

**Issue by bhaettasch** [bhaettasch/pop-buffer-demo#2]
Currently, the application will not work correctly, it the webserver does not support partial requests.

The loader should istead detect the content size of the returned data and do a single load instead of partial loading if already the whole bunch of data was returned.

This should resolve the problem described in #1

**Comment by nxddsnc** [comment]
Do you mean that I should've deleted this part of the code:
    // if(partial)
    // {
    //     begin = begin \* byteCount;
    //     end = (end \* byteCount)-1;
    //
    //     // Set partial load header
    //     oReq.setRequestHeader("Range","bytes="+begin+"-"+end)
    // }
I've tried, but it made no difference:)

**Comment by nxddsnc** [comment]
Hi,
I've walked through the code of encoding. The index reordering part is missing. Maybe that's why.

**Comment by bhaettasch** [comment]
The reordering part is missing since the implementation is not finished yet. Nevertheless, this should not be the reason why the problems occur.

**Comment by bhaettasch** [comment]
Implemented in 9fbaf0e.
